"""Add xp_value field to Badge model

Revision ID: 912276abe38c
Revises: d741f47a405f
Create Date: 2025-04-04 00:45:31.588178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912276abe38c'
down_revision = 'd741f47a405f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_value', sa.Integer(), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('xp_value')

    # ### end Alembic commands ###
