"""Add analytics models

Revision ID: d741f47a405f
Revises: 2043b8dc92f5
Create Date: 2025-04-03 18:43:48.599931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd741f47a405f'
down_revision = '2043b8dc92f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_milestone', 'progress_milestone', ['milestone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_milestone', type_='foreignkey')
        batch_op.drop_column('milestone_id')

    # ### end Alembic commands ###
